/**
 * A header file generated by I2C host driver
 *
 * @file i2c_host_interface.h
 *
 * @defgroup i2c_host I2C_HOST
 *
 * @brief This header file provides the prototypes for the portable firmware interfaces for I2C host.
 *
 * @version I2C Host Interface Version 2.0.5
*/

/*
© [2026] Microchip Technology Inc. and its subsidiaries.

    Subject to your compliance with these terms, you may use Microchip 
    software and any derivatives exclusively with Microchip products. 
    You are responsible for complying with 3rd party license terms  
    applicable to your use of 3rd party software (including open source  
    software) that may accompany Microchip software. SOFTWARE IS ?AS IS.? 
    NO WARRANTIES, WHETHER EXPRESS, IMPLIED OR STATUTORY, APPLY TO THIS 
    SOFTWARE, INCLUDING ANY IMPLIED WARRANTIES OF NON-INFRINGEMENT,  
    MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE. IN NO EVENT 
    WILL MICROCHIP BE LIABLE FOR ANY INDIRECT, SPECIAL, PUNITIVE, 
    INCIDENTAL OR CONSEQUENTIAL LOSS, DAMAGE, COST OR EXPENSE OF ANY 
    KIND WHATSOEVER RELATED TO THE SOFTWARE, HOWEVER CAUSED, EVEN IF 
    MICROCHIP HAS BEEN ADVISED OF THE POSSIBILITY OR THE DAMAGES ARE 
    FORESEEABLE. TO THE FULLEST EXTENT ALLOWED BY LAW, MICROCHIP?S 
    TOTAL LIABILITY ON ALL CLAIMS RELATED TO THE SOFTWARE WILL NOT 
    EXCEED AMOUNT OF FEES, IF ANY, YOU PAID DIRECTLY TO MICROCHIP FOR 
    THIS SOFTWARE.
*/

#ifndef I2C_HOST_INTERFACE_H
#define I2C_HOST_INTERFACE_H

#include <stdbool.h>
#ifndef __XC8
#include <stddef.h>
#endif
#include <stdint.h>
#include "i2c_host_types.h"

/**
 * @ingroup i2c_host
 * @struct i2c_host_interface_t 
 * @brief This structure contains the portable interfaces for I2C host.
 */
typedef struct
{   
    /**
    * @brief Pointer to the function that initializes the I2C host, setting up any necessary hardware or software resources.
    */
    void (*Initialize)(void);
    
    /**
    * @brief Pointer to the function that deinitializes the I2C host, by resetting the I2C registers to Power On Default (POR) values.
    */
    void (*Deinitialize)(void);

    /**
    * @brief Pointer to the write function of the I2C host.
    */
    bool (*Write)(uint16_t address, uint8_t *data, size_t dataLength);

    /**
    * @brief Pointer to the read function of the I2C host.
    */
    bool (*Read)(uint16_t address, uint8_t *data, size_t dataLength);

    /**
    * @brief Pointer to the write and read function of the I2C host.
    */
    bool (*WriteRead)(uint16_t address, uint8_t *writeData, size_t writeLength, uint8_t *readData, size_t readLength);

    /**
    * @brief Pointer to the function that sets up the transfer parameters of the I2C host.
    */
    bool (*TransferSetup)(struct i2c_transfer_setup* setup, uint32_t srcClkFreq);

    /**
    * @brief Pointer to the function that returns the last error that occurred on the I2C bus.
    */
    i2c_host_error_t (*ErrorGet)(void);

    /**
    * @brief Pointer to the function that checks if the I2C bus is busy.
    */
    bool (*IsBusy)(void);

    /**
    * @brief Pointer to the function that Registers a callback function for I2C events.
    */
    void (*CallbackRegister)(void (*callback)(void));

    /**
    * @brief Pointer to the function that is polled for I2C host events.
    */
    void (*Tasks)(void);
}i2c_host_interface_t;

#endif /* I2C_HOST_INTERFACE_H */