/* Microchip Technology Inc. and its subsidiaries.  You may use this software 
 * and any derivatives exclusively with Microchip products. 
 * 
 * THIS SOFTWARE IS SUPPLIED BY MICROCHIP "AS IS".  NO WARRANTIES, WHETHER 
 * EXPRESS, IMPLIED OR STATUTORY, APPLY TO THIS SOFTWARE, INCLUDING ANY IMPLIED 
 * WARRANTIES OF NON-INFRINGEMENT, MERCHANTABILITY, AND FITNESS FOR A 
 * PARTICULAR PURPOSE, OR ITS INTERACTION WITH MICROCHIP PRODUCTS, COMBINATION 
 * WITH ANY OTHER PRODUCTS, OR USE IN ANY APPLICATION. 
 *
 * IN NO EVENT WILL MICROCHIP BE LIABLE FOR ANY INDIRECT, SPECIAL, PUNITIVE, 
 * INCIDENTAL OR CONSEQUENTIAL LOSS, DAMAGE, COST OR EXPENSE OF ANY KIND 
 * WHATSOEVER RELATED TO THE SOFTWARE, HOWEVER CAUSED, EVEN IF MICROCHIP HAS 
 * BEEN ADVISED OF THE POSSIBILITY OR THE DAMAGES ARE FORESEEABLE.  TO THE 
 * FULLEST EXTENT ALLOWED BY LAW, MICROCHIP'S TOTAL LIABILITY ON ALL CLAIMS 
 * IN ANY WAY RELATED TO THIS SOFTWARE WILL NOT EXCEED THE AMOUNT OF FEES, IF 
 * ANY, THAT YOU HAVE PAID DIRECTLY TO MICROCHIP FOR THIS SOFTWARE.
 *
 * MICROCHIP PROVIDES THIS SOFTWARE CONDITIONALLY UPON YOUR ACCEPTANCE OF THESE 
 * TERMS. 
 */

/* 
 * File: MAX7219.h  
 * Author: Kalun Lau 
 * Comments:
 * Revision history: 
 * 19/10/2024 First release
 */ 

// This is a guard condition so that contents of this file are not included
// more than once.  
#ifndef MAX7219_LIB_H
#define	MAX7219_LIB_H

#define max7219_cs LATCbits.LATC0
#define max7219_clk LATEbits.LATE0
#define max7219_data LATEbits.LATE1
#define _XTAL_FREQ 32000000UL

#define COM_SHUTDOWN 0x0C
#define COM_TEST 0x0F
#define COM_INTENSITY 0x0A
#define COM_DECMODE 0x09
#define COM_SCANLIMIT 0x0B

void MAX7219_Init();
void MAX7219_WriteData(unsigned char comando, unsigned char dato);
void MAX7219_WriteData2(unsigned char comando, unsigned char dato);

#endif	/* MAX7219_LIB_H */

